# Generated by Django 6.0.6 on 2026-06-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='Burgers', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cal', models.CharField(blank=True, default='350 cal', max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('table', models.CharField(max_length=50)),
                ('items', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
