# Generated by Django 6.0.3 on 2026-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0003_delete_systemsettings_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_code', models.CharField(default='1234', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
