# Generated by Django 5.0.3 on 2026-06-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0004_systemsettings_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.CharField(max_length=500),
        ),
    ]
